### ISSUE TITLE
Failures installing on macOS

### ISSUE THREAD

**Issue by carlca** [senorprogrammer/wtf#100]
macOS 10.13.5 beta
go1.10.2

```
go get github.com/senorprogrammer/wtf

# github.com/senorprogrammer/wtf/wtf
Code/go/src/github.com/senorprogrammer/wtf/wtf/billboard_modal.go:33:10: textView.SetText undefined (type *tview.TextView has no field or method SetText)
Code/go/src/github.com/senorprogrammer/wtf/wtf/billboard_modal.go:36:10: textView.SetInputCapture undefined (type *tview.TextView has no field or method SetInputCapture)
Code/go/src/github.com/senorprogrammer/wtf/wtf/billboard_modal.go:50:7: thing.SetDrawFunc undefined (type *tview.Frame has no field or method SetDrawFunc)

cd $GOPATH/github.com/senorprogrammer/wtf

CONTRIBUTING.md README.md       bamboohr        dist            git             jira            power           system          weather         wtf_tests
LICENSE.md      _sample_configs clocks          docs            github          newrelic        security        textfile        wtf
Makefile        _site           cmdrunner       gcal            help            opsgenie        status          todo            wtf.go

make install

which wtf | xargs rm
go install -ldflags="-X main.version=v0.0.3-76-g9e49c1_`git rev-parse --abbrev-ref HEAD` -X main.date=2018-05-31T20:38:38+0100"
# github.com/senorprogrammer/wtf/wtf
wtf/billboard_modal.go:33:10: textView.SetText undefined (type *tview.TextView has no field or method SetText)
wtf/billboard_modal.go:36:10: textView.SetInputCapture undefined (type *tview.TextView has no field or method SetInputCapture)
wtf/billboard_modal.go:50:7: thing.SetDrawFunc undefined (type *tview.Frame has no field or method SetDrawFunc)
make: *** [install] Error 2

make run

wtf
make: wtf: No such file or directory
make: *** [run] Error 1
```

Any ideas what's wrong? Thanks!

**Comment by khoyt** [comment]
I am having a similar issue.

`Ken-MBP:wtf ken$ make install
which wtf | xargs rm
go install -ldflags="-X main.version=v0.0.3-76-g9e49c1_`git rev-parse --abbrev-ref HEAD` -X main.date=2018-05-31T15:53:35-0500"
which wtf
make: *** [install] Error 1

Ken-MBP:wtf ken$ make run
wtf
make: wtf: No such file or directory
make: *** [run] Error 1
`
MacOS High Sierra 10.13.4 (17E199)
go version go1.10.2 darwin/amd64

**Comment by carlca** [comment]
This is why we need to see a resolution to the whole vgo/dependency thing resolved as soon as possible. I'll try the tview upgrade and see how that works out.

**Comment by carlca** [comment]
@senorprogrammer Yes that worked. Thanks a lot!

**Comment by senorprogrammer** [comment]
@khoyt Try running `go run wtf.go` and then dump here the error that that command outputs. That might give me a bette idea of what's going wrong.

**Comment by khoyt** [comment]
@senorprogrammer When I ran the command inside the wtf folder, it came up successfully without any errors. I attempted to run wtf as standalone command but it came back with command not found.

**Comment by senorprogrammer** [comment]
@khoyt What do you get if you run `which wtf`? I'm assuming nothing. A small fix was just added to `make install` - perhaps pull the latest and trying again? Otherwise I'm not sure what would be blocking the install.

**Comment by khoyt** [comment]
@senorprogrammer Yeah nothing comes back with `which wtf`. Since it had been awhile since I've ran Go, I checked a few more things.

```
Ken-MBP:wtf ken$ export
...
declare -x GOPATH="/Users/ken/go"
...
```
```
Ken-MBP:wtf ken$ which go
/usr/local/go/bin/go
```
I removed the entire senorprogrammer directory from `/Users/ken/go/src/github.com/`. Then I went through the installation again. Still running into the same error.

```
Ken-MBP:wtf ken$ go get github.com/senorprogrammer/wtf        
Ken-MBP:wtf ken$ cd /Users/ken/go/src/github.com/senorprogrammer/wtf/
Ken-MBP:wtf ken$ make install
which wtf | xargs rm || true
go install -ldflags="-X main.version=v0.0.3-88-gbf4ab1_`git rev-parse --abbrev-ref HEAD` -X main.date=2018-05-31T21:38:47-0500"
which wtf
make: *** [install] Error 1
Ken-MBP:wtf ken$ make run
wtf
make: wtf: No such file or directory
make: *** [run] Error 1
```

**Comment by kirkins** [comment]
Also having problem on Ubuntu 16.04.

Running `which wtf` alone doesn't return anything for me.

**Comment by senorprogrammer** [comment]
@kirkins Which version of Go are you using (`go version`)?

**Comment by kirkins** [comment]
@senorprogrammer `go version go1.9.2 linux/amd64`, not a big `go` user added `/usr/local/go/bin` to path and have `$GOPATH` set.

**Comment by senorprogrammer** [comment]
Thanks. Looks pretty much the same as mine. I'm not sure what the issue could be. I have a Linux VM set up. I'll try to compile it on there this weekend and see what happens.

**Comment by naer2** [comment]
i have same issue.

mac os sierra 10.12.6
go version go1.10.2 darwin/amd64

**Comment by senorprogrammer** [comment]
Going to close this issue out as this is being further explored with a bit of potential progress over here: https://github.com/senorprogrammer/wtf/issues/130
