### ISSUE TITLE
JIRA list includes closed issues, merged, etc.

### ISSUE THREAD

**Issue by hughdbrown** [senorprogrammer/wtf#107]
I've done hundreds of issues at my company, but the list of open JIRA issues displayed in WTF is swamped by all of the closed and merged issues.

In recognition of the custom states that JIRA implementations can have, maybe a filter of key-value pairs would be appropriate.

**Comment by senorprogrammer** [comment]
@hughdbrown I've just merged this commit https://github.com/senorprogrammer/wtf/commit/c43db75561051926c25ade24d254bc91cb493754 in. It allows you to specify custom JQL for Jira queries. Should allow you to customize the query until I implement what you're looking for in a simpler way. 

See the `jql` option here https://wtfutil.com/posts/modules/jira/ for a link to more details.

**Comment by senorprogrammer** [comment]
Going to close this because on reflection, I really like Jql as a solution to this. It provides the most flexibility to people who use it.
