### ISSUE TITLE
Power widget not displaying on MacOS

### ISSUE THREAD

**Issue by Sh1d0w** [senorprogrammer/wtf#108]
MacOS High Sierra OS: 10.13.4

Using the prebuilt binary from the releases tab version 0.0.3

Even if I disable every other widget and leave only power widget to enabled, it does not display at all, only see the black background without event a box or border.

**Comment by senorprogrammer** [comment]
Can you paste your config file in here for me to look at?

**Comment by anmolnagpal** [comment]
@senorprogrammer Hello I'm also getting the same error for power & for ipinfo 
![screen shot 2018-06-02 at 12 27 41 pm](https://user-images.githubusercontent.com/4303310/40872510-630468ca-6660-11e8-957b-9e7b231b5b06.png)

**Comment by senorprogrammer** [comment]
I see the same thing. 0.0.3 doesn't support those modules. I'll be releasing 0.0.4 today, which will fix that issue.

**Comment by senorprogrammer** [comment]
v0.0.4 is available in Releases. Give that a try.

**Comment by anmolnagpal** [comment]
@senorprogrammer let me try give me few min

**Comment by anmolnagpal** [comment]
Both Power && IPInfo looks good. Thank You @senorprogrammer 
<img width="137" alt="screen shot 2018-06-02 at 8 55 17 pm" src="https://user-images.githubusercontent.com/4303310/40878802-51afa4c6-66a7-11e8-86d7-651431578d06.png">

**Comment by senorprogrammer** [comment]
Calling this solved.

**Comment by Sh1d0w** [comment]
@senorprogrammer Sorry for the late replay. All good now, thanks!
