### ISSUE TITLE
Feature: Automated/Smart about which git repo to display

### ISSUE THREAD

**Issue by joeycozza** [senorprogrammer/wtf#115]
I'm not sure if it is even possible, or if possible if it is even worth the effort, but I often switch to many different directories that are repos during the day.

It would really cool if wtf could detect which repo the currently active window/tab was in, and update the git Module automatically.

Like I said, this may not be possible. It would require communication between Terminal windows on each directory change, and then you'd have to worry about different Terminals, and probably other stuff that I don't know about. So, I'm cool with you closing this feature request if you don't even want to consider it. 😄

**Comment by senorprogrammer** [comment]
That'll take a braver dev than me, I have no idea how to hook that up. Going to pass on this one as its not functionality I want or need.
