### ISSUE TITLE
Singular user appended ','

### ISSUE THREAD

**Issue by cryptmin** [senorprogrammer/wtf#117]
@interlock Thank you for your work on the WTF Linux Compatability. 

When there is only a single user session a comma is appended to the username.
![2018-06-01-132212_411x295_scrot](https://user-images.githubusercontent.com/14331760/40854271-df9052fe-659e-11e8-8a0c-f297a89f900b.png)

Consider using `users` instead of `who -us`. Both are GNU CoreUtils.

**Comment by interlock** [comment]
Looks like I should of been trimming spaces and not including zero length lines. Will have a patch up for that in a minute.

My understanding of `users` is it scans the some logs to determine who has a session right now. `who` looks at open tty/ptty. Not sure if I could justify one over the other, so I'll leave it for now.

**Comment by cryptmin** [comment]
A little strace shows that
`users` checks /var/run/utmp 

while 

`who` checks 
- /var/run/utmp
- /var/run/utmpx
and searches for the associated tty regardless of the flag used. 

`users` is less resource intensive based on my research.

I'm nitpicking, I do apologize.

**Comment by interlock** [comment]
You are more than welcome to contribute a change to `users`
