### ISSUE TITLE
Feature: ability to add multiple of the same Module

### ISSUE THREAD

**Issue by joeycozza** [senorprogrammer/wtf#119]
I'd like to use a few different Cmdrunner modules, but it looks like config.ParseYamlFile wouldn't be able to handle objects with the same key, since it appears to use maps underneath. (I have just about zero experience with go).

Also, the makeWidgets function looks like it hard codes a single .newWidget() for each type of Module.

This would probably be a trickier/larger type feature, and it seems like it might need to change the way the config.yaml is structured in order to make it work (from what I can tell. Again, zero go experience).

**Comment by senorprogrammer** [comment]
Same was requested in this issue: https://github.com/senorprogrammer/wtf/issues/111

Not something I want to add, for the reasons described there.

**Comment by senorprogrammer** [comment]
No worries! I expect that to be a fairly common request.
