### ISSUE TITLE
Create gitter channel

### ISSUE THREAD

**Issue by jeangovil** [senorprogrammer/wtf#135]
|    Q        |   A
|------------ | -----
| Version     | 0.0.4
#### Support Question

Please create a Gitter(or any useful app you know) channel. Then anyone can easily ask questions and discuss about problems and ideas that they have.

**Comment by senorprogrammer** [comment]
Gitter channel created: https://gitter.im/wtfutil/Lobby

I'll add it to the docs etc. later.
