### ISSUE TITLE
Make Build/System mod awesome again

### ISSUE THREAD

**Issue by FarhadF** [senorprogrammer/wtf#140]
### Feature Request

|    Q        |   A
|------------ | ------
| New Feature | Kinda
| RFC         | yes
| BC Break    | No
#### Summary

The Build/System mod is available in the default config, hence should be awesome. My current Status:

![spectacle o28816](https://user-images.githubusercontent.com/17374492/40887776-d71c0c4c-6762-11e8-912a-e1f60212521f.png)

As the name implies, Maybe some cool system information with the build time/version would be cool :call_me_hand:

**Comment by senorprogrammer** [comment]
Has been made better by Linux and Windows additions.
