### ISSUE TITLE
Configurable widget titles so people aren't forced to see broken unicode

### ISSUE THREAD

**Issue by senorprogrammer** [senorprogrammer/wtf#143]
### Feature Request

|    Q        |   A
|------------ | ------
| New Feature | yes
| RFC         | no
| BC Break    | no

#### Summary
Currently module titles are hard-coded into the app, in many cases with emoji included. This is both annoying to people who want a different title, and looks poor in terminals that don't support emoji/unicode/utf-8 etc.

Move titles to the config file with plaintext defaults in the app.

**Comment by nabraas** [comment]
لافهم ماذا يريد

**Comment by nabraas** [comment]
🤣🤣🤣🤣🤣

**Comment by senorprogrammer** [comment]
Fixed. All modules now support a `title` value that can include emoji.
