### ISSUE TITLE
Powerline Glyphs Not Showing

### ISSUE THREAD

**Issue by cryptoden** [senorprogrammer/wtf#145]
![123](https://user-images.githubusercontent.com/16755159/40893862-31eb0802-6773-11e8-9fe5-fecdb3ff2950.png)

Tried using multiple powerline fonts, tried terminator + urxvt, also tried Roboto Mono for Powerline.

**Comment by senorprogrammer** [comment]
@cryptoden Did you ever find a solution to this issue?
