### ISSUE TITLE
How to configure wtf with a JIRA instance that uses a self-signed certificate

### ISSUE THREAD

**Issue by juanrubio** [senorprogrammer/wtf#152]
|    Q        |   A
|------------ | -----
| Version     | v0.0.4-70-g5ff80f_master
#### Support Question

I'm trying to run 'wtf' with a JIRA instance that has a self-signed certificate. All the JIRA widget displays is this error message:

```
Get <jira url> .... x509: certificate signed by unknown authority
```
Is there anything I can do to tell wft to skip certificate validation or to simply allow an insecure connection?

Thanks

**Comment by senorprogrammer** [comment]
Sorry, I have no idea. We don't use a hosted version of Jira. If you figure it out, please report back.
