### ISSUE TITLE
make install/run fails

### ISSUE THREAD

**Issue by ChrisCallanJr** [senorprogrammer/wtf#153]
#### Summary
when running `make install`, following error prints out: 
```
which wtf | xargs rm || true
go install -ldflags="-X main.version=v0.0.4-72-g9e77c8_`git rev-parse --abbrev-ref HEAD` -X main.date=2018-06-04T08:30:10-0400"
which wtf
make: *** [install] Error 1
```

and the running `make run`:
```
wtf
make: wtf: No such file or directory
make: *** [run] Error 1```

go version is 1.9.2

**Comment by tcaddy** [comment]
This is what I have to do to make it install:
```bash
cd $GOPATH/src/github.com/senorprogrammer/wtf
go install -ldflags="-X main.version=$(git describe --always --abbrev=6)_$(git rev-parse --abbrev-ref HEAD) -X main.date=$(date +%FT%T%z)"
```

**Comment by ChrisCallanJr** [comment]
@tcaddy Yeah so that appeared to make it install without an error, so after that should I be doing `make run` or `go run`?

**Comment by ChrisCallanJr** [comment]
as an update, running `make run` still prints the same error

**Comment by tcaddy** [comment]
If you run my command, it should place the executable here: `$GOPATH/bin/wtf`
