### ISSUE TITLE
Dialog for new todo item cuts off on portrait oriented displays

### ISSUE THREAD

**Issue by joniler** [senorprogrammer/wtf#168]
#### Summary
When using a portrait mode display (1080x1920), the new todo item dialogue box is cut off on the side of the terminal.

##### What is the current behaviour?
Cut off dialogue.

### How to reproduce
Use WTF in portrait mode fullscreen

##### If the current behaviour is a bug, please provide the steps to reproduce it.
Simply use todo module in portrait fullscreen terminal (screenshot)
![screen shot 2018-06-05 at 9 58 32 am](https://user-images.githubusercontent.com/16842926/40990923-2209d406-68a7-11e8-8c78-94e1fadf86b3.png)

##### What do you think the expected behaviour should be?
I should be able to configure the position in the config.yml file.

**Comment by senorprogrammer** [comment]
The modal should appear in the middle of your monitor like a proper modal. Definitely a bug.

**Comment by danner26** [comment]
This also is occurring for me. 1080p monitor, when it is full screen (actually any size) and you hit n, it will render the new todo item input below the visible area. If you then make the terminal larger, it will show the box (I will add pictures soon)

**Comment by senorprogrammer** [comment]
Thanks. I can reproduce this just be resizing my terminal window. 👍

**Comment by senorprogrammer** [comment]
Should be fixed now. Let me know

**Comment by joniler** [comment]
Fixed! Great job, and thanks for the fast repairs. Use this every day, so I'll be adding things as they come up. <3

**Comment by senorprogrammer** [comment]
You're welcome 🎉
