### ISSUE TITLE
Weather module appears to be broken on master

### ISSUE THREAD

**Issue by senorprogrammer** [senorprogrammer/wtf#173]
#### Summary
Weather module loads immediately with "Weather data is unavailable (1)" error, which suggests it's not connecting to the API.

##### What is the current behaviour?
`Weather data is unavailable (1)` error shows up (found in `weather/display.go:16`).

### How to reproduce
For me, built from current master.

##### What do you think the expected behaviour should be?
On launch an empty widget appears with no weather data. As the API call is made and populates  the data, the data appears.

**Comment by jeangovil** [comment]
a bug in briandowns/openweathermap causes this issue.
![screenshot from 2018-06-06 23-09-03](https://user-images.githubusercontent.com/34973359/41058301-b371b44e-69de-11e8-9baa-4241c64c22cb.png)
I tried to update it with `dep` but I think it just updates it with the latest release.

**Comment by senorprogrammer** [comment]
I imagine that should be `len(key) != 32`?

**Comment by jeangovil** [comment]
Right!

**Comment by senorprogrammer** [comment]
In fact, his `master` has the correct code:
```
func ValidAPIKey(key string) error {
	if len(key) != 32 {
		return errors.New("invalid key")
	}
	return nil
}
```
https://github.com/briandowns/openweathermap/blob/2adae1e5d10290d8cd435bd30296fc5e8f754862/openweathermap.go#L179

**Comment by jeangovil** [comment]
So why it's wrong in vendor directory?

**Comment by senorprogrammer** [comment]
Because it was fixed 21 hours ago after the debs were pulled :) https://github.com/briandowns/openweathermap/commit/93ba6a87d1d2a2047bed13f4a21458f7958147ab

**Comment by rubiojr** [comment]
I'll add a note to the README tomorrow but, in the meantime, `dep ensure -update github.com/foo/bar` will update the dep, `dep ensure -update` will update all deps: https://golang.github.io/dep/docs/daily-dep.html

**Comment by rubiojr** [comment]
Can take care of fixing this one also if nobody beats me to it.

**Comment by jeangovil** [comment]
@rubiojr briandowns/openweathermap did release v0.11.0 3 days ago but also pushed a update to it 22 hours ago. So `dep ensure -update` didn't work. I removed version and added `branch = "master"` in `Gopkg.toml` and it worked.

**Comment by rubiojr** [comment]
@jeangovil I think that's the recommended approach for that particular case: https://github.com/golang/dep/blob/master/docs/FAQ.md#how-do-i-change-the-version-of-a-dependency

**Comment by senorprogrammer** [comment]
Fixed on master. Thanks @rubiojr and @jeangovil for adding and improving `dep` which made it trivial to do.
