### ISSUE TITLE
failing on start with "index out of range" on Windows 7 in either ConEmu64 or PowerShell

### ISSUE THREAD

**Issue by avoll** [senorprogrammer/wtf#176]
stacktrace: 
```
panic: runtime error: index out of range

goroutine 1 [running]:
github.com/senorprogrammer/wtf/vendor/github.com/gdamore/tcell/terminfo.LookupTerminfo(0xc042195808, 0x0, 0xc042195808, 0x0, 0x2c09590)
        D:/dev/Go/src/github.com/senorprogrammer/wtf/vendor/github.com/gdamore/tcell/terminfo/terminfo.go:766 +0x1292
github.com/senorprogrammer/wtf/vendor/github.com/gdamore/tcell.NewTerminfoScreen(0xc042177d10, 0x0, 0xc04206be28, 0xc04206be18)
        D:/dev/Go/src/github.com/senorprogrammer/wtf/vendor/github.com/gdamore/tcell/tscreen.go:40 +0x67
github.com/senorprogrammer/wtf/vendor/github.com/gdamore/tcell.NewScreen(0xc042177ce0, 0x60efb4, 0xce8a40, 0xc0421665a0)
        D:/dev/Go/src/github.com/senorprogrammer/wtf/vendor/github.com/gdamore/tcell/screen.go:203 +0x2d
github.com/senorprogrammer/wtf/vendor/github.com/rivo/tview.(*Application).Run(0xc042177ce0, 0x0, 0x0)
        D:/dev/Go/src/github.com/senorprogrammer/wtf/vendor/github.com/rivo/tview/application.go:80 +0x66
main.main()
        D:/dev/Go/src/github.com/senorprogrammer/wtf/wtf.go:252 +0x483
```

**Comment by webbertakken** [comment]
Same problem here. Exact same error.

**Comment by senorprogrammer** [comment]
Could you try with the latest `master` and let me know? From the error above I don't have enough to know which module is causing the problem, however some Windows-specific improvements went in recently. Wondering if they help.

**Comment by poolofthought** [comment]
I'm having this problem also. Happens in WSL Ubuntu. Powershell, Regular old cmd prompt. Cmder.

Below is the output. I did your simple startup just yesterday so should be all the newest stuff.

`myalias@mypcname:/mnt/c/Users/myuname/go/src/github.com/senorprogrammer/wtf/bin$ ./wtf.exe
panic: runtime error: index out of range

goroutine 1 [running]:
github.com/senorprogrammer/wtf/vendor/github.com/gdamore/tcell/terminfo.LookupTerminfo(0xc04220253a, 0x0, 0xc04220253a, 0x0, 0xc0421a24f0)
        C:/Users/myuname/go/src/github.com/senorprogrammer/wtf/vendor/github.com/gdamore/tcell/terminfo/terminfo.go:766 +0x10c3
github.com/senorprogrammer/wtf/vendor/github.com/gdamore/tcell.NewTerminfoScreen(0xc04219dd80, 0xc042091e48, 0x5fade5, 0xc042091e40)
        C:/Users/myuname/go/src/github.com/senorprogrammer/wtf/vendor/github.com/gdamore/tcell/tscreen.go:40 +0x67
github.com/senorprogrammer/wtf/vendor/github.com/gdamore/tcell.NewScreen(0xc04219dd50, 0xb582c0, 0xc042190360, 0xc042091e90)
        C:/Users/myuname/go/src/github.com/senorprogrammer/wtf/vendor/github.com/gdamore/tcell/screen.go:203 +0x2d
github.com/senorprogrammer/wtf/vendor/github.com/rivo/tview.(*Application).Run(0xc04219dd50, 0x0, 0x0)
        C:/Users/myuname/go/src/github.com/senorprogrammer/wtf/vendor/github.com/rivo/tview/application.go:80 +0x4b
main.main()
        C:/Users/myuname/go/src/github.com/senorprogrammer/wtf/wtf.go:265 +0x39f`

Also, FWIW, my $TERM variable is xterm-256color

**Comment by poolofthought** [comment]
UPDATE: I can run the prebuilt binary on WSL Ubuntu.  But if I build it myself on windows that gives the errors mentioned previously.

**Comment by senorprogrammer** [comment]
It appears that `LookupTerminfo()` inside `tcell`'s `terminfo.go` isn't receiving the `$TERM` name to do a proper lookup on. It's failing on:
```
letter := fmt.Sprintf("%02x", name[0])
```
Interesting.

**Comment by senorprogrammer** [comment]
Could one of you try creating a small Go program that executes this?: `os.Getenv("TERM")`

Something like:
```
func main() {
    fmt.Printf("%v\n", os.Getenv("TERM"))
}
```
and let me know what it returns? Based on the stack trace above, my guess is that call is returning an empty string on your Windows machines.

**Comment by mrmurb** [comment]
Your assumption is correct @senorprogrammer.
Using Windows 10 and PowerShell the return of `os.GetEnv()` is an empty string.

When compiled by using tcell's master branch this problem did not occur.

**Comment by senorprogrammer** [comment]
Cool, I'll update WTF's dependency to the latest. Thanks for digging so deeply into that.

**Comment by senorprogrammer** [comment]
`master` now has the latest tcell `master`. If you could give that a try and let me know if it works, I'd appreciate it.

**Comment by mrmurb** [comment]
Just now fetched the latest code and built w/o problems. It runs as expected under PowerShell.

**Comment by senorprogrammer** [comment]
Thanks for confirming @mrmurb. Considering this one fixed.
