### ISSUE TITLE
The API in ipinfo module has a rate limit.

### ISSUE THREAD

**Issue by Fengyalv** [senorprogrammer/wtf#178]
|    Q        |   A
|------------ | -----
| Version     | 0.0.4
#### Support Question

I kept use the board for a few hours and the ipinfo module display something like `invalid character 'R' looking for beginning of value`。

So I try to get the url in ipinfo, and figured out that the API has a rate limit.

Maybe it is because I use it in my company and someone else use wtf too.

So I changed the API to a free one but kept the display interface same.

Shall I commit the change or you can do some fault tolerance measure?

**Comment by senorprogrammer** [comment]
The IPInfo rate limit is set to 1000 requests per day, which seems pretty reasonable (that's a little under one a minute).

Set `refreshInterval: 120` and you'll stay under the limit.

**Comment by senorprogrammer** [comment]
But if you've got it working with a different IP service, feel free to create a new module with a different name and configuration and I'll add it to the set. Having multiple services to choose from is not a bad thing.

**Comment by Fengyalv** [comment]
Thank you.
Set the refreshinterval seems to solve this problem fine.
And I will create a new module later.
