### ISSUE TITLE
Running wtf in tmux with defaults causes it to crash

### ISSUE THREAD

**Issue by spoike** [senorprogrammer/wtf#179]
#### Summary
Running wtf in tmux fails because it can't seem to determine the terminal entry. According to the [docs, for attributes,](https://wtfutil.com/posts/configuration/attributes/) `term` is an optional attribute in the configuration.

##### What is the current behaviour?

Running wtf after building fails:

```
> make install; make run
which wtf | xargs rm || true
go install -ldflags="-X main.version=v0.0.5-28-g03b729_`git rev-parse --abbrev-ref HEAD` -X main.date=2018-06-07T15:02:15+0200"
which wtf
/<snip-snip>/go/bin/wtf
go build -o bin/wtf
bin/wtf
An error occurred: terminal entry not found
make: *** [run] Error 1
```

Running wtf anywhere after that fails as well with the same error message:

```
> wtf
An error occurred: terminal entry not found
```

##### If the current behaviour is a bug, please provide the steps to reproduce it.
Reproduced in Mac OS 10.13.4 (High Sierra) on MacBook Pro 15".

1. Run tmux
2. Install and run wtf from scratch

##### What do you think the expected behaviour should be?
Should not crash in tmux even though `term` is not set.

### Workaround

Set `term` attribute in the `~/.wtf/config.yml` with a valid option, e.g. `xterm-256color`.

**Comment by deltaxflux** [comment]
With the installer I made it is working properly however a quick fix could be if you add a symlink.

**Comment by deltaxflux** [comment]
Old:

 ```
BRANCH := `git rev-parse --abbrev-ref HEAD`

 

.PHONY: dependencies install run

 

build:

	go build -o bin/wtf

 

install:

	which wtf | xargs rm || true


	go install -ldflags="-X main.version=$(shell git describe --always --abbrev=6)_$(BRANCH) -X main.date=$(shell date +%FT%T%z)"

	which wtf

 

run: build

	bin/wtf

```

New:
```
BRANCH := `git rev-parse --abbrev-ref HEAD`

 

.PHONY: dependencies install run

 

build:

	go build -o bin/wtf

 

install:

	which wtf | xargs rm || true

	go install -ldflags="-X main.version=$(shell git describe --always --abbrev=6)_$(BRANCH) -X main.date=$(shell date +%FT%T%z)"

ln -s $GOPATH/bin/wtf /bin/wtf

	which wtf

 

run: build

	bin/wtf

```
Now it requires root privileges but it should work.

**Comment by deltaxflux** [comment]
Here is the pull request: https://github.com/senorprogrammer/wtf/pull/165

**Comment by senorprogrammer** [comment]
If I understand the comment above correctly, it now requires root to link the app, correct? If so, I'm not a fan of that. Is there a better place than `/bin/wtf` to install it? What about `/usr/local/bin` like Homebrew does?

**Comment by deltaxflux** [comment]
Well, `/usr/bin/wtf` is also fine. Doesn't matter.

**Comment by senorprogrammer** [comment]
I'm going to close this out. I don't believe this is an issue that WTF should explicitly address. If the TERM env var isn't set to a supported definition, or is missing altogether, the underlying framework (tcell) can't reasonably know that the terminal is capable of supporting the minimal set of required functionality. 

The solution, if you don't have TERM globally set, is to set it in WTF's config file and force it.

**Comment by spoike** [comment]
My `TERM` is actually explicitly set in tmux. It is set to `screen-256color-bce` and I believe is a valid value.

In terms of principle of least surprise I wonder if either of the following things could be done:
* Error out with some kind of help to the user. `terminal entry not found. check if $TERM is a valid entry e.g. screen-256color`
* Use a sane default if entry is missing.

**Comment by senorprogrammer** [comment]
Valid values are those defined in `tcell`s `terminfo` collection (which is not yet documented anywhere): https://github.com/gdamore/tcell/tree/master/terminfo

Good idea about improving the error message. Will do.
Also, a sane default is a good idea - does `ansi` make sense?
