### ISSUE TITLE
Add Logging Utility

### ISSUE THREAD

**Issue by BillKeenan** [senorprogrammer/wtf#182]
### Feature Request

|    Q        |   A
|------------ | ------
| New Feature | yes
| RFC         | ??
| BC Break    |no

#### Summary
A simple utility to log to a file in the .wtf directory, that could then be tailed using the text widget

**Comment by BillKeenan** [comment]
this is being addressed here
https://github.com/senorprogrammer/wtf/pull/183

**Comment by senorprogrammer** [comment]
Closed by https://github.com/senorprogrammer/wtf/pull/183
