### ISSUE TITLE
Todo list should scroll onscreen when moving through many items

### ISSUE THREAD

**Issue by senorprogrammer** [senorprogrammer/wtf#207]
#### What's the problem?
When the Todo list has too many items to display onscreen, moving through the list loses the focus offscreen as it moves through items not visible. 

#### How did you expect it to behave?
The Todo list items should scroll onto the screen as the selection moves through them. The selected item should always be visible.

**Comment by bertl4398** [comment]
Hi! I have fixed the scrolling by introducing tview region tags to each todo item and set the ScrollToHighlight method on the underlying textview widget .. I ll open a pull request for this issue.

**Comment by senorprogrammer** [comment]
Fixed in PR #258
