### ISSUE TITLE
Error: terminal entry not found

### ISSUE THREAD

**Issue by retgits** [senorprogrammer/wtf#212]
#### What problem are you having and how can we help?

Not sure if this is a bug or if I was just unlucky, but after running the install instructions provided, I got the error `Error: terminal entry not found`. To fix it, I manually updated the config.yml file to have a key called `term: "xterm-256color"` which solved the issue.

Go: `go version go1.10.2 darwin/amd64`
OS: macOS 10.13.5

**Comment by deltaxflux** [comment]
This is not a problem with wtf. More or less it is a problem with the tcell library which is used. To resolve this simple export the variable like:
`exportTERM=xterm-256color`

You could also add this line in you zshrc or bashrc to resolve this issue.

**Comment by retgits** [comment]
That's what I ended up doing as well :)
