### ISSUE TITLE
Build fails on linux/386: int overflow in NewRelic library

### ISSUE THREAD

**Issue by jongreen-telensa** [senorprogrammer/wtf#218]
#### What's the problem?

The wtf build doesn't seem to be happy with linux/386 golang, even given the most recent version. I'm guessing this is a 32/64 bit clash problem. Unfortunately, due to my beginner-level knowledge of golang at present, I'm not able to diagnose and fix.

Setup:

Vanilla new install of golang:

```
jgreen@dt-jgreen-01 github.com/senorprogrammer/wtf$ uname -a
Linux dt-jgreen-01 4.9.0-6-686-pae #1 SMP Debian 4.9.88-1+deb9u1 (2018-05-07) i686 GNU/Linux
jgreen@dt-jgreen-01 github.com/senorprogrammer/wtf$ go version
go version go1.10.3 linux/386
```
Having downloaded the wtf sources:

```
jgreen@dt-jgreen-01 github.com/senorprogrammer/wtf$ make install
go clean
go install -ldflags="-X main.version=v0.0.9-25-g343612 -X main.date=2018-06-21T11:53:14+0100"
# github.com/senorprogrammer/wtf/vendor/github.com/yfronto/newrelic
vendor/github.com/yfronto/newrelic/alert_events_test_fixtures.go:40:18: constant 1472355451353 overflows int
Makefile:10: recipe for target 'install' failed
make: *** [install] Error 2
```

#### How did you expect it to behave?

Expected a clean build and install

**Comment by senorprogrammer** [comment]
Thanks for the comment, I can reproduce the issue with:
```
~/go/src/github.com/senorprogrammer/wtf master
❯ env GOARCH=386 go build -o ftw
# github.com/senorprogrammer/wtf/vendor/github.com/yfronto/newrelic
vendor/github.com/yfronto/newrelic/alert_events_test_fixtures.go:40:18: constant 1472355451353 overflows int
```

**Comment by senorprogrammer** [comment]
I've opened this PR on the main project: https://github.com/yfronto/newrelic/pull/61 to fix the issue.

**Comment by senorprogrammer** [comment]
In the meantime I've committed a local patch (https://github.com/senorprogrammer/wtf/commit/24a46a652b7f4ad98518784d75f6cc2cb89c0313). Give it a try now.

**Comment by jongreen-telensa** [comment]
Thanks, the patch works well.
