### ISSUE TITLE
Jenkins module causing crash

### ISSUE THREAD

**Issue by dragoon** [senorprogrammer/wtf#221]
#### What's the problem?
I have a problem configuring Jenkins module, I have set up the environment variable, username and the url and receive the following crash:

```
panic: invalid character '<' looking for beginning of value
goroutine 26 [running]: github.com/senorprogrammer/wtf/jenkins.parseJson(0x157b4c0, 0xc42015a070, 0x1748fe0, 0xc42037c340)
 /Users/chris/go/src/github.com/senorprogrammer/wtf/jenkins/client.go:61 +0x1cb

```
#### How did you expect it to behave?
I expect it to not crash or tell me what the problem is.

**Comment by senorprogrammer** [comment]
When a JSON parser dies with that kind of error it usually means it's receiving HTML instead of JSON.

I suspect your Jenkins configuration is incorrect and as such it's receiving an HTML error message.

**Comment by dragoon** [comment]
Is it possible to know what URL is called by the plugin? Because I checked from the browser and correctly received a JSON response.

**Comment by senorprogrammer** [comment]
It looks like it's the URL you defined in your config plus `/api/json?pretty=true` on the end of that.

**Comment by dragoon** [comment]
Okay I guess I have a problem with Jenkins then, not sure why it works in the browser but does not work with curl.

**Comment by dragoon** [comment]
Started to work after I regenerated the token. However, I'm now getting a different error:
`json: cannot unmarshal object into Go struct field View.property of type string`
Do you know what this could mean?

**Comment by senorprogrammer** [comment]
The `View` struct used to deserialize the JSON payload has a field called `Property` in it. It's expecting an array of strings (`Property    []string `json:"property"``) and for some reason the JSON you're getting back doesn't conform to that.

Is my guess. I don't actually use Jenkins so I don't have this module running to know exactly what the payload looks like, or what `Property` means per se inside a Jenkins install.

**Comment by dragoon** [comment]
Thanks, now I figured out it needs a view url from jenkins and not an url of a specific job.
