### ISSUE TITLE
PrettyWeather has no color

### ISSUE THREAD

**Issue by ammo888** [senorprogrammer/wtf#222]
#### What's the problem?
Pretty Weather doesn't display color
Mac OS High Sierra
iTerm 2, zsh

<img width="559" alt="screen shot 2018-06-22 at 12 07 06 pm" src="https://user-images.githubusercontent.com/3614587/41786916-cec1e272-7614-11e8-9f6d-d1df94dfbfbc.png">

**Comment by BillKeenan** [comment]
well, the byte array is getting printed out.

so you see [38;5;226m , thats the byt sequence to set the screen to yellow.

**Comment by senorprogrammer** [comment]
@BillKeenan I had a similar idea. A lookup table of sorts like https://github.com/senorprogrammer/wtf/blob/master/wtf/colors.go that maps xterm colours to tcell colour names. Seems like a good idea to me, though I'm also curious about why the byte array isn't been interpreted by the terminal as colours. There's something there I'm not understanding.

**Comment by BillKeenan** [comment]
yeah, i haven't gone into the display part of wtf..

**Comment by D-Nice** [comment]
same issue on void linux, urxvt, bash.

**Comment by bertl4398** [comment]
Hi!
after having the same issue and some digging it looks like tview has its own handling of ANSI escape codes and provides a function to replace ANSI escape sequences with tview's colour tags TranslateANSI (or TranslateANSII some commits ago)

https://godoc.org/github.com/rivo/tview#TranslateANSI

although, this function didn't work for me for colour codes above 16 :(

so I wrote a little helper function to do the already mentioned replacement 

https://gist.github.com/bertl4398/feac43dd6bd6094a25a4110854940e66

if you like I can do a pull request or feel free to copy the code and use/modify it .. for a quick fix you can just download the colors.go and place it next to the weatherservices/prettyweather/widget.go and use the ASCIItoTviewColors function e.g.

widget.result = strings.TrimSpace(ASCIItoTviewColors(string(contents)))

**Comment by senorprogrammer** [comment]
Brilliant, thank you! I've added this into WTF for PrettyWeather and I'll genericize it for elsewhere. A number of widgets could use this.

**Comment by senorprogrammer** [comment]
Very nice. <img width="160" alt="screen shot 2018-07-18 at 3 06 02 pm" src="https://user-images.githubusercontent.com/6413/42910383-31cf0f0c-8a9c-11e8-88ca-6fe31da10f78.png">
