### ISSUE TITLE
Proposal: Re-work format of calendar view

### ISSUE THREAD

**Issue by baustinanki** [senorprogrammer/wtf#223]
#### What problem does this solve?

For a set of mocked-up fake events, here's what the current calendar view looks like:

![](https://i.imgur.com/995yEzJ.png)

There's nothing particularly wrong with it, but there are a couple ways I think it could be improved.

The most important aspect of an event - when it takes place - is somewhat tucked away, towards the end of the third line of an event. If you want to tell from just a glance when you're next going be pulled away from your desk, it's not the most obvious place to look.

Another important aspect of calendars is getting a sense of, from looking at it, "what is my day like today?" The grouping of events (with only an extra blank line separating one day from the next) doesn't give a lot of visual encapsulation of what makes up your "day".

#### How do envision it working?

I propose a format somewhat like the following (feedback/suggestions welcome):

![](https://i.imgur.com/drtf5iX.png)

- Centered date across the top makes it clear which block of space constitutes each day
- Time of each event is front and center at the beginning of it, also makes events look "sorted"
- By having the date centered at the start of each day, we don't have to repeat it for each event, allowing us to consolidate information to 2 lines instead of 3, leaving room for more events in the same amount of space

Depending on what people think, this could be an option (we could have some predefined formats that you select from in the config), or we could go full-on git-pretty-formatting with % specifiers and stuff to allow full customization (that's obviously a more complicated change). But, in general, I've been using this format locally for the last week or so and I really like it.

**Comment by senorprogrammer** [comment]
When you say you've been using it locally, does that mean you could have a PR to commit that back against master? Because I like the look of what you've done a lot. Makes a lot of sense to me.

**Comment by baustinanki** [comment]
>does that mean you could have a PR to commit that back against master?
There are a couple pieces I should clean up first but yeah, I could have a PR of that pretty soon.

**Comment by senorprogrammer** [comment]
If you're playing along at home, the PR for this is here: https://github.com/senorprogrammer/wtf/pull/224

**Comment by senorprogrammer** [comment]
Closed with this PR https://github.com/senorprogrammer/wtf/pull/224
