### ISSUE TITLE
Just got "Error: character set not supported"

### ISSUE THREAD

**Issue by Jaydonjin** [senorprogrammer/wtf#225]
#### I just got "Error: character set not supported",when i'm running wft.exe with default config.yml.
$ wtf.exe
Error: character set not supported

**Comment by mapitman** [comment]
This is happening because the tcell package always returns "UTF-16" when you call [charset.getCharset()](https://github.com/gdamore/tcell/blob/de7e78efa4a71b3f36c7154989c529dbdf9ae623/charset_windows.go#L19). Then the call to encoding.GetEncoding() fails because there is no encoder for UTF-16 defined in [encodings](https://github.com/gdamore/tcell/blob/de7e78efa4a71b3f36c7154989c529dbdf9ae623/encoding.go#L131)

I'm not sure what the _right_ way is to fix this, but I thought I'd at least add this info to the issue since I spent the time to debug through it.

**Comment by senorprogrammer** [comment]
That's interesting. I'll open an issue on `tcell` to see what @gdamore thinks about that. Thanks for the investigation @mapitman.

**Comment by gdamore** [comment]
Hmm... the problem there is that UTF-16 is weird (there are actually two variants of it, big endian and little endian), and tcell doesn't expect to see these multibyte encodings on terminal displays. 

That said, I'm surprised this is blocking you.  Is this in WSL, or real Windows console?

**Comment by gdamore** [comment]
Huh, UTF-16LE is automatically supported.  I suspect that this problem is something else, like attempting to use tcell apps inside a mingw terminal.  That winds up with this sort of failure.

**Comment by gdamore** [comment]
(More specifically, that encodings array is only meant to be used when the stock golang encodings support is absent.)

**Comment by senorprogrammer** [comment]
@Jaydonjin does any of that help you with your issue?

**Comment by mapitman** [comment]
@gdamore 

> Is this in WSL, or real Windows console?
When I received the error, I was running in git-bash. 

When I run in `cmd.exe` I get the following output:

```
panic: runtime error: index out of range

goroutine 1 [running]:
github.com/senorprogrammer/wtf/vendor/github.com/gdamore/tcell/terminfo.LookupTerminfo(0xc0421d40c8, 0x0, 0xc0421d40c8, 0x0, 0x8)
        C:/Users/mpitman/go/src/github.com/senorprogrammer/wtf/vendor/github.com/gdamore/tcell/terminfo/terminfo.go:766 +0x10c3
github.com/senorprogrammer/wtf/vendor/github.com/gdamore/tcell.NewTerminfoScreen(0x5eaae9, 0xc042254000, 0xc0421dc330, 0xc042087e28)
        C:/Users/mpitman/go/src/github.com/senorprogrammer/wtf/vendor/github.com/gdamore/tcell/tscreen.go:40 +0x67
github.com/senorprogrammer/wtf/vendor/github.com/gdamore/tcell.NewScreen(0xc04218b0a0, 0xc04218b0a0, 0xc042087e68, 0x5f5469)
        C:/Users/mpitman/go/src/github.com/senorprogrammer/wtf/vendor/github.com/gdamore/tcell/screen.go:203 +0x2d
github.com/senorprogrammer/wtf/vendor/github.com/rivo/tview.(*Application).Run(0xc04218b0a0, 0x0, 0x0)
        C:/Users/mpitman/go/src/github.com/senorprogrammer/wtf/vendor/github.com/rivo/tview/application.go:80 +0x59
main.main()
        C:/Users/mpitman/go/src/github.com/senorprogrammer/wtf/wtf.go:270 +0x3a4
```

**Comment by senorprogrammer** [comment]
@mapitman Does it make any difference if you explicitly set the `wtf.term` config value in your config file (see here: https://wtfutil.com/posts/configuration/attributes/)? Something like:

```
wtf:
    term: xterm-256color
```

I suspect you have an empty string for your $TERM ENV var.

**Comment by Jaydonjin** [comment]
I am so sorry for my failure to respond in time.
But,WTF is still not working.
I tried this way in MINGW32 :

```bash
go get -u github.com/senorprogrammer/wtf
cd $GOPATH/src/github.com/senorprogrammer/wtf
go instll
make run
```
``` bash
$ make run
go build -o bin/wtf
bin/wtf
Error: character set not supported
make: *** [run] Error 1
```

**Comment by senorprogrammer** [comment]
Inside your config file (`~/config/wtf/config.yml`), add the `wtf.term` config value. See here for details: https://wtfutil.com/posts/configuration/attributes/

Try the example value `xterm-256color` and see if that helps.

**Comment by gdamore** [comment]
Tcell, and hence wtf, won’t work with mingw inside mintty.

You need to use a real Windows console window, or a “capable” one like
ConEmu.

Someday I’ll try to figure out how to make stuff work sanely inside mintty,
but its not terrifically high on my priority list — mintty is bizarre
hybrid between Windows and UNIX terminals, and lacks sufficient
functionality to work correctly as either a UNIX terminal or as a Windows
terminal.  (To get full featured Windows you have to use “magic” like
winpty, or have code that understands specifically this bizarre set of
circumstances and handles it better.)

Given that “real windows consoles” work quite well, and given that I can’t
seem to get any real information about how to work around this problem, a
fix for this has been quite low priority for me.

 - Garrett

**Comment by senorprogrammer** [comment]
Thanks for the info and insight @gdamore. As such I think this one can be closed as "won't fix".

**Comment by Jaydonjin** [comment]
jj51@wcmis043 /d/go_workspace/src/github.com/senorprogrammer/wtf/bin
$ wtf --config=../config.yml
Error: character set not supported

config.yml
```bash
wtf:
  colors:
    background: "red"
    border:
      Focusable: "darkslateblue"
      focused: "orange"
      normal: "gray"
  grid:
    # How _wide_ the columns are, in terminal characters. In this case we have
    # six columns, each of which are 35 characters wide
    columns: [35, 35, 35, 35, 35, 35]

    # How _high_ the rows are, in terminal lines. In this case we have five rows
    # that support ten line of text, one of three lines, and one of four
    rows: [10, 10, 10, 10, 10, 3, 4]
  # The app redraws itself once a second
  refreshInterval: 1
  term: "xterm-256color"
```

**Comment by Jaydonjin** [comment]
In windows cmd

``` bash
D:\go_workspace\src\github.com\senorprogrammer\wtf\bin>wtf --config=../config.yml
Error: character set not supported
```

**Comment by senorprogrammer** [comment]
No, I was incorrect. It's as @gdamore says: "Tcell, and hence wtf, won’t work with mingw inside mintty"

See his suggestions above for possible alternative options for running WTF on Windows.

**Comment by Jaydonjin** [comment]
"use a real Windows console" @gdamore  said
Is cmd.exe not real windows console?

**Comment by gdamore** [comment]
cmd.exe actually isn’t a console, but it starts one.  (This is a bit
weirder.)  If you’re getting this error a standard Windows cmd.exe window,
then you probably have $TERM (or %TERM% rather) set.  Try unsetting it.
 (This is actually reasonably a bug in tcell that I should fix — when we
are running on Windows we should just use the Windows APIs unconditionally.)

 - Garrett

**Comment by Jaydonjin** [comment]
Thank you for your help~ @gdamore
