### ISSUE TITLE
TMUX issue

### ISSUE THREAD

**Issue by mgarcia-accesso** [senorprogrammer/wtf#231]
#### What's the problem?
When running wtf in a tmux window, vertical bars are all preceded and followed by '17'

#### How did you expect it to behave?
Not rendering '17' all over the screen 

[Screenshots](https://imgur.com/a/cCk1pud)

**Comment by deltaxflux** [comment]
Confirmed. Bug priority: high.

**Comment by senorprogrammer** [comment]
Try explicitly setting the `wtf.term` config value to something other than what it is in tmux. Try `ansi`, `xterm`, or `xterm_256color`.

**Comment by senorprogrammer** [comment]
I suspect you have `$TERM` set to `vt100` which will cause what you're seeing.

**Comment by deltaxflux** [comment]
nope

**Comment by deltaxflux** [comment]
Now you could try:
```
tmux
wtf
```

**Comment by mgarcia-accesso** [comment]
Apologies for the slow response, and thank you for your rapid ones. This corrected: 
wtf:
  term: xterm-256color
First line in config, worked like a charm.

**Comment by senorprogrammer** [comment]
Awesome!
