### ISSUE TITLE
Highlight synatax_files not included in compiled binary

### ISSUE THREAD

**Issue by winks** [senorprogrammer/wtf#261]
#### What's the problem?
Downloaded 0.1.0 on Ubuntu 16.04 and ran it.

the bottom right window (of 4 in a square, 1 status at the very bottom) displays:

```
┌─ Text File  ~/.config/wtf/config.yml─┐ 
│open /home/florian/code/go/src/github.│
│com/senorprogrammer/wtf/vendor/github.│
│com/zyedidia/highlight/syntax_files:  │
│no such file or directory 
```

#### How did you expect it to behave?

"No config file found" or "missing dependency: `highlight/syntax_files`

I am actually unsure if it tries to load something dynamically after startup.

**Comment by senorprogrammer** [comment]
I believe that's a missing dependency. Are you using the binary or compiling from source?

**Comment by winks** [comment]
downloaded the binary release, that's why I'm puzzled

**Comment by senorprogrammer** [comment]
Oh, I bet I know what's going on. The [`highlight` package](https://github.com/zyedidia/highlight) contains a directory of `yaml` files that it uses to highlight syntax. It's not included in the compiled binary. As a work-around for the time being, you can install them via: `go get github.com/zyedidia/highlight` if you have Go installed.

And thanks for catching that and opening an issue on it! I appreciate it.
