### ISSUE TITLE
Does not support ~ in config file paths

### ISSUE THREAD

**Issue by senorprogrammer** [senorprogrammer/wtf#295]
#### What's the problem?
When specifying a custom config file path, cannot use `~`:
```
wtf --config=~/Desktop/simple_config.yml

2018/08/13 09:29:56 main.go:169: stat /Users/ccummer/go/src/github.com/senorprogrammer/wtf/~/Desktop/simple_config.yml: no such file or directory
```

#### How did you expect it to behave?
Treat that as the home directory and path from there.

**Comment by deltaxflux** [comment]
Using `~` is mostly a bad idea because `~` doesn't extend to the full path. Better is **$HOME** because this extend to the full path like `/home/<user>`. So this a minor problem.
