### ISSUE TITLE
Spotify controller module

### ISSUE THREAD

**Issue by StormFireFox1** [senorprogrammer/wtf#305]
#### What problem does this solve?
I have recently downloaded this program and have used it consistently on all my devices. One thing I do find important in my developer workflow, however, is music. It would be cool if WTF had a music player (possibly linked with Spotify) module that could be added on the grid.

#### How do envision it working?
It would be a module that would contain the media player's current song info, etc (no need for album image) and would have a few keys (like p, left and right arrow) to play/pause, change song, etc. The integration with Spotify would probably be a lot easier than it seems, as well. (considering there are libraries to interface with Spotify in Go)

**Comment by senorprogrammer** [comment]
That would be awesome. I hope someone builds this.

**Comment by anandsudhir** [comment]
Can this be closed now?  #317 has been merged

**Comment by senorprogrammer** [comment]
Good idea. I'll do that as soon as I add some documentation for the Spotify module.

**Comment by senorprogrammer** [comment]
Added by @sticreations sticreations.

**Comment by StormFireFox1** [comment]
Thank you very much for this! Whenever I get time, I'll try to contribute and add Windows support for this module.

**Comment by senorprogrammer** [comment]
That would be great. Looking forward to rolling that in @StormFireFox1

**Comment by sticreations** [comment]
I actually wanted to do that, but it seems that OSX and Windows don’t have something like linuxes dbus. So you would have to use the Spotify API. 
My goal was to have as little configuration as possible, but I think using the api would be way more easier to generalize than finding a hacky way to control it via something else.

**Comment by StormFireFox1** [comment]
I found a Web API for Spotify written in Go:

https://github.com/zmb3/spotify

This should technically work, but for a normal user, it takes time to configure that some might not put in.
If I find a way to make the current version of the widget work with Windows as well, I'll do that. Otherwise, the package linked seems reasonable enough.

**Comment by voldemortensen** [comment]
I submitted a PR to @sticreations package that adds OSX support via apple script: https://github.com/sticreations/spotigopher/pull/3

**Comment by senorprogrammer** [comment]
@StormFireFox1 That looks interesting indeed. I would support the adoption of either a) a single Spotify module that can be configured to work with either the web API or the local client, or b) two Spotify modules, one for the web API and one for the local client.
