### ISSUE TITLE
Gcal widget does not display all-day events

### ISSUE THREAD

**Issue by senorprogrammer** [senorprogrammer/wtf#306]
#### What's the problem?
Events that are marked as "all-day" do not display in the calendar listing.

#### How did you expect it to behave?
I should see all-day events, indicated as such, in the daily listing.

#### Operating system 
MacOS

#### Terminal program & version
iTerm2

#### WTF version
master

**Comment by linux923344** [comment]
Also I see, it has not got Others Calendars

**Comment by nicholas-eden** [comment]
I fixed all day events.  The Others Calendars will be a tough one I think.

**Comment by senorprogrammer** [comment]
Fixed by @nicholas-eden
