### ISSUE TITLE
Documentation issue: API token permissions

### ISSUE THREAD

**Issue by lyda** [senorprogrammer/wtf#316]
#### What's the problem?

Module documentation for [github](https://wtfutil.com/posts/modules/github/) and possibly other modules missing API token permission requirements.

#### How did you expect it to behave?

The [gitlab module](https://wtfutil.com/posts/modules/gitlab/) has good documentation here. Other API token vars should have similar documentation.

#### Operating system 

N/A

#### Terminal program & version

N/A

#### WTF version

This is with `HEAD` but this applies to the published docs, not the binary itself.

**Comment by senorprogrammer** [comment]
GitHub documentation now links to this blog post: [Personal API tokens](https://blog.github.com/2013-05-16-personal-api-tokens/)
