### ISSUE TITLE
Add support for firewall on linux

### ISSUE THREAD

**Issue by TheRedSpy15** [senorprogrammer/wtf#331]
#### What problem does this solve?
Adds the ability to check firewall status on Linux

#### How do envision it working?
Running a system command, getting the result, and return a status based on the command result

**Comment by TheRedSpy15** [comment]
I would be happy to make a pull request for this, if that's alright

**Comment by senorprogrammer** [comment]
Please do!

**Comment by TheRedSpy15** [comment]
Made a pull request! #333

**Comment by senorprogrammer** [comment]
Added in https://github.com/senorprogrammer/wtf/pull/333
