### ISSUE TITLE
Calendar pane should be able to subscribe to multiple gcal accounts

### ISSUE THREAD

**Issue by bhardy** [senorprogrammer/wtf#47]
I have my work calendar and my home calendar both displayed in my calendar app. Ideally I'd be able to see meetings/appointments from each within a single WTF calendar pane.

**Comment by senorprogrammer** [comment]
@lsipii added this functionality in https://github.com/senorprogrammer/wtf/pull/211
It's in `master` now and will be released in `v0.0.9`.
