### ISSUE TITLE
Todo Widget: Can move unchecked todos to bottom(after checked todos) 

### ISSUE THREAD

**Issue by jeangovil** [senorprogrammer/wtf#73]
We should not be able to move unchecked todos below checked todos.
Also when uncheck any todo and try to go down the list, it starts at the old position of that todo item.

**Comment by senorprogrammer** [comment]
I'm not a fan of limiting how people move things around in the list. If someone wants to have their latest  unchecked item be at the bottom, so be it (maybe it's very low priority item). I'm thinking the feature of having checked items move down the list automatically should probably be flag-enabled so someone else can turn it off if they like.

**Comment by jeangovil** [comment]
I agree, we can add a option in config file. But I'm saying at this time(when this feature is automatically on) there is a bug. We should be able to move an item down but not after checked items(Right? If no, then why add this feature? everyone can move checked items to bottom by themselves)

**Comment by jeangovil** [comment]
I agree, we can add an option in config file.
I thought there is a bug. But still there is another.
After we uncheck an item and try to select another item, selector starts at the old position of unchecked item.

**Comment by jeangovil** [comment]
It was a really small bug(sorry for that 😔). fixed it.

**Comment by senorprogrammer** [comment]
Nice work. Fix is merged.

**Comment by senorprogrammer** [comment]
Added.
