### ISSUE TITLE
Github widget crashes on refresh when there's no network connection

### ISSUE THREAD

**Issue by matrinox** [senorprogrammer/wtf#75]
### Problem
I have only used the Github widget and I find it crashes when you have no internet and it either automatically refreshes or you manually refresh it. This can also happen when you put your computer on standby.

### Steps to Reproduce
- Configure wtf with Github widget
- Disable wifi and other internet sources
- Press ctrl+R

**Expected result**: user-friendly error message without crashing
**Actual result**: crashes

### Screenshots
Attached is a screenshot of this happening:
<img width="1780" alt="screen shot 2018-05-30 at 11 19 20 am" src="https://user-images.githubusercontent.com/4261980/40739826-0c9fd91c-63fc-11e8-958c-d800a37ba2d0.png">

**Comment by senorprogrammer** [comment]
```bash
github.com/senorprogrammer/wtf/github/github_repo.go:40
github.com/senorprogrammer/wtf/github.(*Widget).displayStats(0xc42017a360, 0xc420089130, 0x5b, 0x15bfdc8)
github.com/senorprogrammer/wtf/github/display.go:67 +0x44
github.com/senorprogrammer/wtf/github.(*Widget).display(0xc42017a360)
github.com/senorprogrammer/wtf/github/display.go:22 +0x2a6
github.com/senorprogrammer/wtf/github.(*Widget).Refresh(0xc42017a360)
github.com/senorprogrammer/wtf/github/widget.go:63
```

**Comment by matrinox** [comment]
Forgot to mention, I only filed a bug for Github cause that's what I'm testing but perhaps we should check other widgets using internet like JIRA?

**Comment by senorprogrammer** [comment]
Yep, very much so. The expected behaviour is to show the raised error in the widget textview. This is easy enough to test by disabling the Github widget and trying again.
