### ISSUE TITLE
Doesn't isntall/build

### ISSUE THREAD

**Issue by prologic** [senorprogrammer/wtf#77]
```
$ go get github.com/senorprogrammer/wtf
# github.com/senorprogrammer/wtf/github
go/src/github.com/senorprogrammer/wtf/github/github_repo.go:90:30: pr.RequestedReviewers undefined (type *github.PullRequest has no field or method RequestedReviewers)
```

**Comment by senorprogrammer** [comment]
@prologic Could you try running this: `go get -u github.com/google/go-github/github` and then running the installation instructions again? Google added `RequestedReviewers` to that package fairly recently; I'm wondering if you've got an older version installed.

**Comment by senorprogrammer** [comment]
Solution for now is `go get -u github.com/google/go-github/github`. See https://github.com/senorprogrammer/wtf/issues/93 for other examples of this problem.

**Comment by prologic** [comment]
👍
