### ISSUE TITLE
Support for github enterprise

### ISSUE THREAD

**Issue by SEJeff** [senorprogrammer/wtf#82]
This should work exactly the same as the normal github integration, but requires a host to connect to the github api (since it is on premise or in a vpc).

**Comment by senorprogrammer** [comment]
I'd happily take that in a PR as either a config option (specify the host, connect there instead), or as a  new `githubent` module. I don't have access to GitHub Enterprise to test that out myself.

**Comment by amrnt** [comment]
https://github.com/senorprogrammer/wtf/pull/122 🎉

**Comment by senorprogrammer** [comment]
Added by @amrnt here https://github.com/senorprogrammer/wtf/pull/122
