### ISSUE TITLE
Support setting background color

### ISSUE THREAD

**Issue by jessemillar** [senorprogrammer/wtf#84]
In [Hyper](https://hyper.is/), WTF draws a gray background around its contents. I would love to be able to configure the color of the background or (preferably) make the background transparent so my terminal's normal background color shows instead.

![screen shot 2018-05-31 at 9 28 38 am](https://user-images.githubusercontent.com/4627837/40788159-01e60ad2-64b5-11e8-9d1a-d6a71d74dce4.png)

**Comment by senorprogrammer** [comment]
Added as a config option: `wtf.colors.background`. See `Attributes` documentation or the sample config files for an example.
