### ISSUE TITLE
Dynamic column sizes?

### ISSUE THREAD

**Issue by jessemillar** [senorprogrammer/wtf#85]
Would it be difficult to add config options for min and max column sizes than can scale a bit based on the terminal's current size? I use a [window manager](https://github.com/koekeishiya/chunkwm) so my terminal doesn't always spawn at the same width and height.

**Comment by bbrks** [comment]
If you configure the grid with no columns or rows, the grid will stretch to fit the whole terminal, and you can use top/left/height/width of a module as a relative unit.

```yml
wtf:
  grid:
    columns: []
    rows: []
```

**Comment by jessemillar** [comment]
Ah. Yup. That totally works. Solves my problem. Closing.
