### ISSUE TITLE
The NewRelic plugin makes wtf crash.

### ISSUE THREAD

**Issue by bogdanr** [senorprogrammer/wtf#86]
As soon as wtf tries to talk to the NewRelic API the app crashes with the following message:
![snapshot1](https://user-images.githubusercontent.com/1079875/40789080-3c9c4692-64fa-11e8-9d21-1716fb000ffc.png)

If the API key is not correct then it just tells just that and it works fine.

**Comment by senorprogrammer** [comment]
Thanks for the stack trace. I'll take a look.

**Comment by senorprogrammer** [comment]
Fixed by @lasanthak in https://github.com/senorprogrammer/wtf/commit/6a72e8c182ccaf240476e872f96d25875ecacb62
