### ISSUE TITLE
Website: bottom of left menu inaccessible on some resolutions/zoom levels

### ISSUE THREAD

**Issue by milkmiruku** [senorprogrammer/wtf#91]
My screen resolution is 1366x768. My default browser zoom level is 110%. At that, the lowest module link is 'Security'. At 100% it's 'Todo'. I can't scrollwheel or 'drag-scroll' further down, I have to zoom out to see the full list.

**Comment by senorprogrammer** [comment]
Thanks for pointing out this usability issue. I appreciate it.

**Comment by senorprogrammer** [comment]
Sidebar now scrolls with the rest of the site. Let me know how that works (I'm not concerned about the minor cosmetic issue on longer pages, I'll fix that another time).

**Comment by senorprogrammer** [comment]
Ok, that was a false start. But now the sidebar should scroll with the rest of the page and all the content in the sidebar should remain visible. Let me know how that works out.
