### ISSUE TITLE
Linux Support

### ISSUE THREAD

**Issue by cryptmin** [senorprogrammer/wtf#94]
The "Security" modules only support OSX. Please add support for Linux, or utilize a library that enables cross-platform compatibility. 

Love the design and idea behind the application! Great work!

**Comment by interlock** [comment]
I'm about half done doing this right now. It's quite... Ubuntu specific, but that probably hits a good chunk of people.

**Comment by nkoehring** [comment]
@interlock can you elaborate on "ubuntu specific"?

**Comment by senorprogrammer** [comment]
Awesome. If someone puts up a PR, I'll merge it in.

**Comment by interlock** [comment]
@nkoehring Sure can.

Wifi and DNS data comes from `nmcli` which I am not sure is commonly installed with most distros. 

Users is filtered from `who`, which is POSIX so :+1: for that

I could find no way to determine firewall state without `sudo` so put a a less assuming "NA" in it's place.

**Comment by nkoehring** [comment]
@interlock nmcli is NetworkManager, common in most graphically rich distros. WTF is more focused on skilled users, so I would assume a good percentage isn't using NetworkManager (me included). There's iwconfig (old) and iwtools (current) for that which should be available on Ubuntu alike Systems too

**Comment by interlock** [comment]
@nkoehring good to know. I updated the PR to use `iwgetid` for the network name, but I can't find any tools around getting the encryption. Any suggestions?

**Comment by senorprogrammer** [comment]
Added with this commit: https://github.com/senorprogrammer/wtf/commit/a88a909e1060fbda54bdbbea6eb7166983aed419
