### ISSUE TITLE
wrong chronological sorted clocks

### ISSUE THREAD

**Issue by nkoehring** [senorprogrammer/wtf#98]
When I set the world times to chronological sorting, they are sorted wrong. The timezones in my config are GMT, Europe/Berlin, Turkey, Australia/Perth (which is how they should be sorted). Their sorting switches from Berlin, Perth, GMT, Turkey and Turkey, Perth, GMT, Berlin.

**Comment by nkoehring** [comment]
Not a go programmer, but I guess this line is somehow not sorting the way you expect it to:
https://github.com/senorprogrammer/wtf/blob/9e49c18c44b6d4aa36f3bf8e42681496bde55e00/clocks/clock_collection.go#L35

**Comment by Dieterbe** [comment]
+1 same problem. for me the order seems to constantly jump around. quite annoying.
otherwise, great looking project!
PS: could also be cool to have asc vs desc setting
